/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-01-08 10:40:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1546939004000L));
    _jspx_dependants.put("jar:file:/E:/workspace/backend/eclispe-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JspAndServlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; UTF-8;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.getContextPath() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.getContextPath() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/custom.css\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<div class=\"container-fluid nav-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logo-lisaho.png\" alt=\"logo-page\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logo-southbank.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"logo-page\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 phone-contact\">\r\n");
      out.write("\t\t\t\t\t\t<b class=\"phone-contact-content\">HOTLINE: 0963.9999.30 -\r\n");
      out.write("\t\t\t\t\t\t\t0909.343.048</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1 phone-contact\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"phone-contact-content\" href=\"#\">Login</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t<div class=\"banner-wrapper container\">\r\n");
      out.write("\t\t\t\t<div class=\"slide-banner\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/slide.jpg\" alt=\"slide-banner\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form class=\"register-form\" action=\"#\" name=\"signupForm\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<h6>HỌC VIỆN CÔNG NGHỆ SOUTHBANK, ÚC</h6>\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title-form\">Bạn còn thắc mắc về du học Úc? Vui\r\n");
      out.write("\t\t\t\t\t\tlòng để lại thông tin dưới đây, chúng tôi sẽ liên hệ tư vấn nhanh\r\n");
      out.write("\t\t\t\t\t\tnhất</p>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Họ và tên\"> <input class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"number\" name=\"phone\" placeholder=\"Điện thoại\"> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"address\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Nơi ở ...</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Hà Nội</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">Đà Nẵng</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">TP.HCM</option>\r\n");
      out.write("\t\t\t\t\t</select> <select class=\"form-control\" name=\"graduation\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Bạn đã tốt nghiệp?</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Chưa tốt nghiệp</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">Đã tốt nghiệp</option>\r\n");
      out.write("\t\t\t\t\t</select> <select class=\"form-control\" name=\"major\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Ngành đăng kí</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Quản trị kinh doanh</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">Công nghệ thông tin</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">Lịch sử đảng</option>\r\n");
      out.write("\t\t\t\t\t</select> <input class=\"form-control\" type=\"text\" placeholder=\"Email\"\r\n");
      out.write("\t\t\t\t\t\tname=\"email\">\r\n");
      out.write("\t\t\t\t\t<button id=\"submitButton\" class=\"btn btn-default\">Đăng kí</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t<section class=\"section1\">\r\n");
      out.write("\t\t\t<p class=\"title\">CÁC BƯỚC ĐỂ DU HỌC THÀNH CÔNG</p>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/add-1.jpg\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">BƯỚC 1: ĐĂNG KÍ</p>\r\n");
      out.write("\t\t\t\t\t<p>Đăng kí để lại thông tin của bạn</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/add-2.jpg\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">BƯỚC 2:ĐƯỢC TƯ VẤN TỪ BỘ PHẬN TUYỂN SINH</p>\r\n");
      out.write("\t\t\t\t\t<p>Chuyên gia tư vấn của chúng tôi sẽ giúp bạn chọn ngành học\r\n");
      out.write("\t\t\t\t\t\tphù hợp</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/add-3.jpg\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">BƯỚC 3: HOÀN THÀNH HỒ SƠ</p>\r\n");
      out.write("\t\t\t\t\t<p>Chuyên gia tư vấn sẽ hỗ trợ bạn hoàn thành hồ sơ nhập học và\r\n");
      out.write("\t\t\t\t\t\tvisa chu đáo</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/add-4.jpg\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">BƯỚC 4: TRẢI NGHIỆM HỌC TẬP QUỐC TẾ</p>\r\n");
      out.write("\t\t\t\t\t<p>Bắt đầu học tập tại môi trường giáo dục hàng đầu thế giới</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class=\"section1-submit btn btn-default\">Đăng ký</button>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section2\">\r\n");
      out.write("\t\t\t<p class=\"title\">LỢI ÍCH KHI THAM GIA HỌC TẬP TẠI HỌC VIỆN\r\n");
      out.write("\t\t\t\tSOUTHBANK</p>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-1.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>Không cần thi đầu vào</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-2.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>Không cần chứng minh tài chính</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-3.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>Học phí và phí sinh hoạt cạnh tranh</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-4.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>Đội ngũ giáo viên là chuyên gia trong các lĩnh vực chuyên\r\n");
      out.write("\t\t\t\t\t\tmôn, giàu kinh nghiệm trong việc giảng dạy học sinh quốc tế</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-5.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>250 chương trình chuyển tiếp vào các trường Đại học hàng đầu\r\n");
      out.write("\t\t\t\t\t\tcủa Úc sẽ giúp sinh viên hoàn thành con đường học vấn đỉnh cao</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-6.jpg\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t<p>Sau khi tốt nghiệp học sinh được phép ở lại thêm 2 năm làm\r\n");
      out.write("\t\t\t\t\t\tviệc ở Úc</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section3\">\r\n");
      out.write("\t\t\t<p class=\"title\">LỢI ÍCH KHI LÀM HỒ SƠ DU HỌC TẠI CÔNG TY LISAHO</p>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-2-1.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">VỀ CHÚNG TÔI</p>\r\n");
      out.write("\t\t\t\t\t<p>Công ty tư vấn du học LisaHo do ông Kelvin Chu - người Úc,\r\n");
      out.write("\t\t\t\t\t\tcó nhiều kinh nghiệm trong lĩnh vực đào tạo và giáo dục nghề tại\r\n");
      out.write("\t\t\t\t\t\tÚc thành lập. Là đại diện tuyển sinh chính thức của Học viện công\r\n");
      out.write("\t\t\t\t\t\tnghệ SOUTHBANK</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-2-2.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">GIÁ TRỊ \"3C\"</p>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tHọc sinh nhận được sự tư vấn hoàn thiện:<br> - Củng cố nền\r\n");
      out.write("\t\t\t\t\t\ttảng<br> - Chọn trường phù hợp<br> - Cơ hội nghề nghiệp\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-2-3.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">MIỄN PHÍ TƯ VẤN 100%</p>\r\n");
      out.write("\t\t\t\t\t<p>Chuyên gia tư vấn sẽ hỗ trợ bạn hoàn thành hồ sơ nhập học và\r\n");
      out.write("\t\t\t\t\t\tvisa chu đáo</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/benefit-2-4.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sub-title\">QUÀ TẶNG GIÁ TRỊ</p>\r\n");
      out.write("\t\t\t\t\t<p>Bắt đầu học tập tại môi trường giáo dục hàng đầu thế giới</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section4\">\r\n");
      out.write("\t\t\t<p class=\"title\">NGÀNH ĐÀO TẠO &amp; ĐỐI TƯỢNG TUYỂN SINH</p>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/object-left.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/object-right.png\" alt=\"step1-image\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<p>KHAI GIẢNG: THÁNG 07/2014 VÀ THÁNG 01/2015</p>\r\n");
      out.write("\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/go-to-top.png\" alt=\"\">\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("js");
      // /WEB-INF/views/home.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(4,0) '${request.getContextPath() }assets/js'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${request.getContextPath() }assets/js",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("images");
      // /WEB-INF/views/home.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(5,0) '${request.getContextPath() }assets/images'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${request.getContextPath() }assets/images",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
